#print_head "install maven"
#yum install maven -y &>>$log_file
#func_stat_check $?





- name: install maven
  ansible.builtin.yum:
    name: maven

- name: Include app_prerequisites
  ansible.builtin.import_tasks:
    file: app_prereq.yml 

- name: download maven dependencies
  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar     
  args:
    chdir: /app

- name: include schema setup
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: include systemd 
  ansible.builtin.import_tasks:
    file: systemd_setup.yml

- name: import prometheus
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter    



