#print_head "install maven"
#yum install maven -y &>>$log_file
#func_stat_check $?



#func_app_prereq

#print_head "download maven dependencies"
#mvn clean package &>>$log_file
#func_stat_check $?
#mv target/${component}-1.0.jar ${component}.jar &>>$log_file

#func_schema_setup
#func_systemd_setup

- name: install maven
  ansible.builtin.yum:
    name: maven

- name: Include app_prerequisites
  ansible.builtin.import_tasks:
    file: app_prereq.yml 

- name: download maven dependencies
  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar     
  args:
    chdir: /app

- name: include schema setup
  ansible.builtin.import_tasks:
    file: schema_setup.yml

