


#func_schema_setup
#func_systemd_setup

- name: Configuring nodejs repos
  ansible.buitin.shell: 
    cmd: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash" 

- name: install nodejs
  ansible.buitin.yum: 
    name: nodejs
    state: installed

- name: Include app_prerequisites
  ansible.builtin.import_tasks:
    file: app_prereq.yml 

- name: install nodejs dependencies
  ansible.buitin.shell: npm install
  args:
    chdir: /app
