 #print_head "install Python"
#yum install python36 gcc python3-devel -y &>>$log_file
#func_stat_check $?

#func_app_prereq



#print_head "install python dependencies"
#pip3.6 install -r requirements.txt &>>$log_file
#func_stat_check $?

#print_head "update passwods in system service file"
#sed -i -e "s|rabbitmq_appuser_password|${rabbitmq_appuser_password}|" ${script_path}/payment.service &>>$log_file
#func_stat_check $?

#func_systemd_setup

 

- name: install python
  ansible.builtin.yum: 
    name:  
      - python36 
      - gcc 
      - python3-devel 
    state: installed

- name: Include app_prerequisites
  ansible.builtin.import_tasks:
    file: app_prereq.yml 

- name: install python dependencies    
   ansible.buitin.shell: pip3.6 install -r requirements.txt
    args:
    chdir: /app


- name: include schema setup
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: include systemd 
  ansible.builtin.import_tasks:
    file: systemd_setup.yml


