#if [ "$schema_setup" == "mongo" ]; then
#print_head "copy mongodb repo"
#cp ${script_path}/mongo.repo /etc/yum.repos.d/mongo.repo &>>$log_file
#func_stat_check $?

#print_head "install mongodb client"
#yum install mongodb-org-shell -y &>>$log_file
#func_stat_check $?


#print_head "load schema"
#mongo --host mongodb.devops1722.com </app/schema/${component}.js &>>$log_file
#func_stat_check $? 
#fi